[[post]]
category = "Data Science Roadmap"
title = "Working on it..."
subtitle = "I am currently working to share with you resources such as: books, blogs, websites, courses among others that might interest you."
datetime = "2024-01-01"
image = "./config/assets/projects/canvas.min.webp"
url = "https://github.com/LuisGTZB"

