[[doing]]
title = "Data Science"
icon = "./config/assets/icons/bar-chart.svg"
text = "I'm currently learning data science and have approximately one year of experience in the professional area."

[[doing]]
title = "Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using Python to enhance efficiency and productivity."

[[doing]]
title = "DBA"
icon = "./config/assets/icons/database.svg"
text = "Database administration and related data management activities."

[[doing]]
title = "Web Development"
icon = "./config/assets/icons/laptop-code.svg"
text = "High-quality development of sites at the professional level using HTML, CSS and JS."
