[[project]]
title = "Working on it..."
category = "Mobile development"
image = "./config/assets/projects/canvas.min.webp"
url = "https://github.com/LuisGTZB"

[[project]]
title = "Web Scrapping for page changes detection"
category = "Python Scripting"
image = "./config/assets/projects/Web-Scraping.png"
url = "https://github.com/LuisGTZB/WebScrappingJCF"

[[project]]
title = "Genetic Algorithm using OneMax"
category = "Python Scripting"
image = "./config/assets/projects/project-12.jpg"
url = "https://github.com/LuisGTZB/Genetic_Algorithm"

[[project]]
title = "Product Manager Application"
category = "Web development"
image = "./config/assets/projects/project-11.png"
url = "https://github.com/LuisGTZB/AplicacionWeb"

[[project]]
title = "ChatBot-Interface"
category = "Web development"
image = "./config/assets/projects/project-10.PNG"
url = "https://github.com/LuisGTZB/Chatbot_Interface"

[[project]]
title = "Analysis of environmental inspection and surveillance actions in Mexico"
category = "Data Project"
image = "./config/assets/projects/project-14.PNG"
url = "https://github.com/LuisGTZB/hacking-civico/blob/master/proyecto/Proyecto_Hacking_civico.ipynb"

[[project]]
title = "Working on it..."
category = "Applications"
image = "./config/assets/projects/canvas.min.webp"
url = "https://github.com/LuisGTZB"

[[project]]
title = "Data analysis of a solar energy company."
category = "Data analysis of a solar energy company"
image = "./config/assets/projects/project-13.PNG"
url = "https://github.com/LuisGTZB/Bright"


