############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
python = "./config/assets/icons/python.svg"
jupyter = "./config/assets/icons/jupyter.svg"
pandas = "./config/assets/icons/pandas.svg"
css = "./config/assets/icons/CSS3.svg"
scikit-learn = "./config/assets/icons/scikit-learn.svg"
flask = "./config/assets/icons/Flask.svg"
matplotlib = "./config/assets/icons/Matplotlib.svg"
numpy = "./config/assets/icons/numpy.svg"
r = "./config/assets/icons/R.svg"
postgresql = "./config/assets/icons/PostgresSQL.svg"
postman = "./config/assets/icons/Postman.svg"
c = "./config/assets/icons/C.svg"
anaconda = "./config/assets/icons/Anaconda.svg"
java = "./config/assets/icons/Java.svg"
javascript = "./config/assets/icons/JavaScript.svg"
flutter = "./config/assets/icons/flutter.svg"
git = "./config/assets/icons/git.svg"
figma = "./config/assets/icons/figma.svg"
mongodb = "./config/assets/icons/mongodb.svg"
dart = "./config/assets/icons/dart.svg"
html = "./config/assets/icons/html.svg"
# firebase = "./config/assets/icons/firebase.svg"
# ai = "./config/assets/icons/ai.svg"
# linux = "./config/assets/icons/linux.svg"